# Generated by Django 2.2.2 on 2019-07-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20190709_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_token',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
