# Generated by Django 2.2.2 on 2019-06-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190617_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='register_as',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
