# Generated by Django 2.2.2 on 2019-06-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_register_as'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='users/default_profile.jpg', upload_to='users'),
        ),
    ]
