# Generated by Django 2.2.2 on 2019-06-18 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='requests',
        ),
    ]
