# Generated by Django 2.2.2 on 2019-08-19 17:27

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_profile_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='users'),
        ),
    ]
