# Generated by Django 2.2.2 on 2019-08-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190819_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='users/default_profile.jpg', upload_to='users'),
        ),
    ]
