# Generated by Django 2.2.2 on 2019-08-20 13:34

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190820_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='users/default_profile.jpg', upload_to=users.models.upload_to),
        ),
    ]
