# Generated by Django 2.2.2 on 2019-07-03 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0011_auto_20190702_1010'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='rental',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maintenance.Rental'),
        ),
    ]
