# Generated by Django 2.2.2 on 2019-07-19 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0015_auto_20190717_1559'),
        ('chat', '0002_thread_rental'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='thread',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='maint_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maintenance.MaintRequest'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='maint_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maintenance.MaintRequest'),
        ),
    ]
