# Generated by Django 2.2.2 on 2019-08-16 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20190719_1623'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
