# Generated by Django 2.2.2 on 2019-06-17 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_auto_20190616_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=30)),
                ('postcode', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=15)),
                ('no_of_tenants', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='maintrequest',
            name='property_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.Rental'),
        ),
    ]
