# Generated by Django 2.2.2 on 2019-06-18 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_auto_20190617_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintRequestImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='mantenance/no_image.jpg', upload_to='maintenance')),
            ],
        ),
        migrations.AddField(
            model_name='maintrequest',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.MaintRequestImage'),
        ),
    ]
