# Generated by Django 2.2.2 on 2019-06-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_auto_20190618_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='image',
            field=models.ImageField(default='mantenance/no_image.jpg', upload_to='maintenance'),
        ),
    ]
