# Generated by Django 2.2.2 on 2019-07-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_rental_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintrequest',
            old_name='date_occurred',
            new_name='date_raised',
        ),
        migrations.AlterField(
            model_name='maintrequest',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('med', 'Med'), ('high', 'High')], max_length=20),
        ),
        migrations.AlterField(
            model_name='maintrequest',
            name='status',
            field=models.CharField(choices=[(None, 'Status'), ('new', 'New'), ('in-progress', 'In Progress'), ('awaiting-payment', 'Awaiting Payment'), ('resolved', 'Resolved')], default='new', max_length=20),
        ),
    ]
