# Generated by Django 2.2.2 on 2019-07-01 16:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0008_auto_20190701_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintrequest',
            name='date_raised',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
