# Generated by Django 2.2.2 on 2019-07-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0011_auto_20190702_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='image',
            field=models.ImageField(default='maintenance/no_image.jpg', upload_to='maintenance'),
        ),
    ]
