# Generated by Django 2.2.2 on 2019-07-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0013_auto_20190704_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintrequest',
            name='cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='maintrequest',
            name='invoice_pdf',
            field=models.FileField(null=True, upload_to='maintenance'),
        ),
        migrations.AddField(
            model_name='maintrequest',
            name='paid_by',
            field=models.CharField(choices=[('tenant', 'Tenant'), ('landlord', 'Landlord')], max_length=20, null=True),
        ),
    ]
