# Generated by Django 2.2.2 on 2019-07-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0014_auto_20190713_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintrequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in-progress', 'In Progress'), ('awaiting-payment', 'Awaiting Payment'), ('resolved', 'Resolved')], default='new', max_length=20),
        ),
    ]
