# Generated by Django 2.2.2 on 2019-07-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0015_auto_20190717_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='postcode',
            field=models.CharField(max_length=8),
        ),
    ]
