# Generated by Django 2.2.2 on 2019-12-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0016_auto_20190728_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintrequest',
            name='invoice_pdf',
            field=models.FileField(blank=True, null=True, upload_to='maintenance'),
        ),
    ]
