# Generated by Django 2.2.2 on 2019-12-02 21:47

from django.db import migrations, models
import maintenance.models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0017_auto_20191202_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintrequest',
            name='paid_by',
            field=models.CharField(choices=[('Tenant', 'Tenant'), ('Landlord', 'Landlord')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='image',
            field=models.ImageField(default='maintenance/no_image.jpg', upload_to=maintenance.models.upload_to),
        ),
    ]
